### ISSUE TITLE
Cannot add complete folder structure in Pack Maker

### ISSUE THREAD

**Issue by stephanmoe** [davidgevorgian/ESP8266UpdatePack#1]
Hi there,
thanks for your great work! 

To pack also webcontents with folder structure (e.g. /home/src/test.html) it would be great if we can also select the folder as a whole and import the complete content with the correct pathname.
At the moment we only can select each file seperatly in each folder and edit the pathname to the correct pathname what's very time-consuming...

Thanks again and best regards,
Stephan

**Comment by stephanmoe** [comment]
Are there any news? :)
Best regards, Stephan

**Comment by davidgevorgian** [comment]
Thank you,

I put the source into GITHUB. Check dir PkgMaker.
Only I did not understand what the problem was?

Regards,
David

**Comment by stephanmoe** [comment]
Thanks for that!

The problem was that I can only add single SPIFFS files right now.
In case of big webpages with many files and subdirectories it's a little bit creepy to select every single file and change the "Name" to the correct relative path.

A perfect solution could be a button e.g. "Add folder" that will add all files as well as subfolders within this folder with just one click. Here it is important to change the "Name" of the files that are located in the subfolders.. Because they are in the subfolder we need to add the relative path in front of the files' name e.g. **/subfolder/FilesName** .

At the end it could looks like following:
![image](https://user-images.githubusercontent.com/19521200/30502372-3fa4c710-9a66-11e7-86de-b4354496bdce.png)

I've sadly never worked with Delphi. I would be very pleased if you could supporting me on this point :)

Thanks and best regards,
Stephan

**Comment by davidgevorgian** [comment]
Accepted,
I'm very busy, but I'll try to help you.
Give me a few days and I'll add this feature.

**Comment by stephanmoe** [comment]
Sure, no problem!
Thanks in advance! :+1:

**Comment by davidgevorgian** [comment]
Please check, i added the function by you request. Good luck.
![screenshot1](https://user-images.githubusercontent.com/16103132/30525201-12190bd4-9c0b-11e7-9ab1-ed71f0d5f421.png)

Best Regards,
David

**Comment by stephanmoe** [comment]
Thanks for your fast reply!
It works nearly perfect! Thanks! :+1:  

The only problem now is when I have files in folders with subfolders and subfolders they will not be added.
Our folder structure looks like following ("data" is the main or reference folder)
![image](https://user-images.githubusercontent.com/19521200/30544545-1fccd086-9c87-11e7-9e16-82b83fe367d1.png)

It would be great if all data in the folder and the data in the subfolders will be added inclusive their correct paths.

Btw. could you please remove the name of the main folder in front of the files name? The name of the folder should only be added for the subfolders and their subfolders... 
The main folder should be the reference for this structure. Therefore please delete the name of the main folder in the file's name.

Would you please be so kind and help me again regarding this problem? :)

Thanks in advance and best regards,
Stephan

**Comment by davidgevorgian** [comment]
Then what you ask is much more difficult, it's easier to create a new program. I'm now very busy with the project, when possible I will make a new one. Marked in my scheduler.

Best Regards,
David

**Comment by davidgevorgian** [comment]
By the way, you can use multi-select for choose the right files...

**Comment by stephanmoe** [comment]
Thanks for your help! 
That would be absolutely ok! I'm looking forward to hearing from you :)
In parallel I will start implementing your arduino code into mine..

Thanks for the hint! That could be very useful if you only add files from one folder..
My problem right now is more that the most SPIFFS files are located in many folders/subfolders/sub- subfolders.. this is the reason why I need more a tool that walk through every folder/subfolder and adds every single file in every folder with the correct relative path name.. 

Anyway don't hurry! Please take your time :) 
I'm more than happy that you can support me at this point.

Thanks for your help and best regards,
Stephan

**Comment by davidgevorgian** [comment]
Stephan,
You can Check, the new version Pack Maker 2.0

Regards,
David

**Comment by stephanmoe** [comment]
David,
wow that works perfect! That's exactly what I was looking for!
Thanks for your efforts! :+1: 

For more security the next challenge would be to encrypt and decrypt the code on both sides. 
Right now all Strings that are stored in flash are human readable in the generated .bin file.
I would favor a system where the developer can define a static key on both sides and only with this key the ESP can decrypt and read the SPIFFS and firmware files.
With this it shouldn't be possible anymore to reengineer the code and find vulnerabel points to hack the system.
Would you be so kind and help me at this point a little bit? :)

In the meantime I will adapt your example code to an AsyncWebServer and upload the code. Maybe this could also be interesting for someone else..

Thanks again and best regards,
Stephan
